// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  window.golab = window.golab || {};

  window.golab.tools = window.golab.tools || {};

  window.golab.tools = window.golab.tools || {};

  window.golab.tools.configuration = window.golab.tools.configuration || {};

  window.golab.tools.configuration["conceptmapper"] = {
    debug: {
      type: "boolean",
      value: "true"
    },
    auto_load: {
      type: "boolean",
      value: "true"
    },
    actionlogging: {
      type: "string",
      value: "console"
    },
    show_prompts: {
      type: "boolean",
      value: "true"
    },
    textarea_concepts: {
      type: "boolean",
      value: "true"
    },
    combobox_concepts: {
      type: "boolean",
      value: "true"
    },
    drop_external: {
      type: "boolean",
      value: "true"
    },
    concepts: {
      type: "array",
      value: ["length", "mass", "time", "electric current", "thermodynamic temperature", "amount of substance", "luminous intensity"]
    },
    relations: {
      type: "array",
      value: ["is a", "is part of", "has", "leads to", "influences", "increases", "decreases"]
    }
  };

}).call(this);

/*
//@ sourceMappingURL=configuration_default.map
*/
