development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: amval
  password: semanticpm

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: amval
  password: semanticpm

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: amval
  password: semanticpm