// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var createEnvironmentHandlers, document;

  this.golab = this.golab || {};

  this.golab.common = this.golab.common || {};

  if (false) {
    document = document || {};
    document.URL = document.URL || {};
    window.location = window.location || {};
  }

  createEnvironmentHandlers = function(documentType, toolName, desiredLanguage, callBack) {
    var checkForReady, languageHandlerCallBack, metadataHandlerCallback, recievedLanguageHandler, recievedMetadataHandler;
    recievedMetadataHandler = null;
    recievedLanguageHandler = null;
    checkForReady = function() {
      var actionLogger, notificationClient, storageHandler;
      if (recievedMetadataHandler && recievedLanguageHandler) {
        storageHandler = new window.golab.ils.storage.LocalStorageHandler(recievedMetadataHandler);
        actionLogger = new window.ut.commons.actionlogging.ActionLogger(recievedMetadataHandler);
        notificationClient = new window.ude.commons.NotificationClient(recievedMetadataHandler);
        return callBack(recievedMetadataHandler, storageHandler, actionLogger, recievedLanguageHandler, notificationClient);
      }
    };
    metadataHandlerCallback = function(error, metadataHandler) {
      if (error) {
        return console.error("failed to create metadataHandler: " + error);
      } else {
        recievedMetadataHandler = metadataHandler;
        return checkForReady();
      }
    };
    languageHandlerCallBack = function(error, languageHandler) {
      if (error) {
        console.error("failed to create languageHandler: " + error);
        recievedLanguageHandler = "none";
        return checkForReady();
      } else {
        recievedLanguageHandler = languageHandler;
        return checkForReady();
      }
    };
    new window.golab.ils.metadata.GoLabMetadataHandler({
      "actor": {
        "objectType": "person",
        "id": "user_123",
        "displayName": "Jon Doe"
      },
      "target": {
        "objectType": documentType,
        "id": ut.commons.utils.generateUUID(),
        "displayName": "unnamed " + documentType
      },
      "generator": {
        "objectType": "application",
        "url": window.location.href,
        "id": ut.commons.utils.generateUUID(),
        "displayName": toolName
      },
      "provider": {
        "objectType": "ils",
        "url": window.location.href,
        "id": ut.commons.utils.generateUUID(),
        "inquiryPhase": "unknown",
        "displayName": "unknown"
      }
    }, metadataHandlerCallback);
    return window.golab.createLanguageHandler(desiredLanguage, languageHandlerCallBack);
  };

  this.golab.common.createEnvironmentHandlers = createEnvironmentHandlers;

}).call(this);

/*
//@ sourceMappingURL=createEnvironmentHandlers_local_testing.map
*/
