// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  window.ut = window.ut || {};

  ut.commons = ut.commons || {};

  ut.commons.DataSource = (function() {
    function DataSource() {}

    DataSource.prototype.getRowValues = function(dataSourceColumnArray) {
      /*
       return an array of arrays
       at top level, each element is new row
      */

    };

    return DataSource;

  })();

  ut.commons.DataSourceColumn = (function() {
    function DataSourceColumn() {}

    DataSourceColumn.prototype.getImageInformation = function() {
      throw new Error("ut.tools.dataviewer.DataSourceColumn.getImageInformation() is not overriden");
      /*
        type         value
        commonImage  name of image
        image        absolute path of image
      */

      return {
        type: "",
        value: ""
      };
    };

    DataSourceColumn.prototype.getType = function() {
      throw new Error("ut.tools.dataviewer.DataSourceColumn.getType() is not overriden");
      /*
        returns "string", "number" or "boolean"
      */

    };

    DataSourceColumn.prototype.getId = function() {
      throw new Error("ut.tools.dataviewer.DataSourceColumn.getId() is not overriden");
    };

    DataSourceColumn.prototype.getLabel = function() {
      throw new Error("ut.tools.dataviewer.DataSourceColumn.getLabel() is not overriden");
    };

    DataSourceColumn.prototype.getUnit = function() {
      throw new Error("ut.tools.dataviewer.DataSourceColumn.getUnit() is not overriden");
    };

    return DataSourceColumn;

  })();

  ut.commons.DataSourceColumnDrop = (function() {
    function DataSourceColumnDrop() {}

    DataSourceColumnDrop.prototype.getDataSource = function() {
      throw new Error("ut.tools.dataviewer.DataSourceColumnDrop.getType() is not overriden");
    };

    DataSourceColumnDrop.prototype.getDataSourceColumns = function() {
      return [this.getDataSourceColumn()];
    };

    DataSourceColumnDrop.prototype.getDataSourceColumn = function() {
      throw new Error("ut.tools.dataviewer.DataSourceColumnDrop.getType() is not overriden");
    };

    return DataSourceColumnDrop;

  })();

}).call(this);

/*
//@ sourceMappingURL=dataSource.map
*/
