// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.ut = window.ut || {};

  window.ut.tools = window.ut.tools || {};

  window.ut.tools.LanguageHandler = (function() {
    function LanguageHandler(localeFile) {
      this.localeFile = localeFile != null ? localeFile : "locale/ALL_ALL.xml";
      this.getMsg = __bind(this.getMsg, this);
      this._initStandalone = __bind(this._initStandalone, this);
      console.log("Initializing LanguageHandler.");
      if (typeof gadgets !== "undefined" && gadgets !== null) {
        this.gadgetPrefs = new gadgets.Prefs();
        console.log("... running inside OpenSocial, using host local: " + (this.gadgetPrefs.getLang()) + "}");
      } else {
        console.log("... running standalone, using locale: " + this.localeFile);
        this._initStandalone();
      }
      this;
    }

    LanguageHandler.prototype._initStandalone = function() {
      var bundle, xhttp,
        _this = this;
      if (window.XMLHttpRequest) {
        xhttp = new XMLHttpRequest();
      } else {
        xhttp = new ActiveXObject("Microsoft.XMLHTTP");
      }
      xhttp.open("GET", this.localeFile, false);
      xhttp.send();
      bundle = xhttp.responseXML;
      this.standaloneBundle = {};
      $.each($("msg", bundle), function(index, msg) {
        var key, value;
        key = $(msg).attr('name');
        value = $(msg).text();
        _this.standaloneBundle[key] = value;
        return console.log("added to bundle: " + key + ": " + value);
      });
      return this;
    };

    LanguageHandler.prototype.getMsg = function(key) {
      if (key != null) {
        if (typeof gadgets !== "undefined" && gadgets !== null) {
          return this.gadgetPrefs.getMsg(key);
        } else {
          return this.standaloneBundle[key];
        }
      } else {
        throw "Cannot get a message string without a key.";
      }
    };

    return LanguageHandler;

  })();

}).call(this);

/*
//@ sourceMappingURL=LanguageHandler.map
*/
