// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var initialMetadata;

  initialMetadata = {
    "actor": {
      "objectType": "person",
      "id": "f25d7eff-8859-49ed-85e9-e7c1f92bc334",
      "displayName": "anonymized"
    },
    "target": {
      "objectType": "dummy objectType",
      "id": "9383fbbe-e071-49b2-9770-46ddc4f8cd6e",
      "displayName": "dummy displayName"
    },
    "generator": {
      "objectType": "test",
      "url": "http://go-lab.gw.utwente.nl/experiments/...",
      "id": "04123e9e-14d0-447b-a851-805b9262d9a6",
      "displayName": "stress test tool"
    },
    "provider": {
      "objectType": "stresstest",
      "url": "http://go-lab.gw.utwente.nl/experiments/...",
      "id": "0f8184db-53ba-4868-9208-896c3d7c25bb",
      "displayName": "stresstest"
    }
  };

  new golab.ils.metadata.MetadataHandler(initialMetadata, function(error, metadataHandler) {
    var actionLogger, i, logObject, _i, _results;
    metadataHandler.setActor({
      "objectType": "person",
      "id": "f25d7eff-8859-49ed-85e9-e7c1f9212345",
      "displayName": "Stressor"
    });
    actionLogger = new ut.commons.actionlogging.ActionLogger(metadataHandler);
    actionLogger.setLoggingTargetByName("dufftown");
    _results = [];
    for (i = _i = 1; _i <= 1000; i = ++_i) {
      logObject = {
        "objectType": "stressObject",
        "id": ut.commons.utils.generateUUID(),
        "content": i
      };
      _results.push(actionLogger.log("stress", logObject));
    }
    return _results;
  });

}).call(this);

/*
//@ sourceMappingURL=logStressTest.map
*/
